yatube/Yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/urls.py
# posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index),
    path('group/', views.group_list),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )

yatube/posts/views.py
# posts/views.py
from django.shortcuts import render, get_object_or_404

from .models import Post, Group


def index(request):
    # Одна строка вместо тысячи слов на SQL:
    # в переменную posts будет сохранена выборка из 10 объектов модели Post,
    # отсортированных по полю pub_date по убыванию (от больших значений к меньшим)
    posts = Post.objects.order_by('-pub_date')[:10]
    # В словаре context отправляем информацию в шаблон
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def group_list(request):
    return HttpResponse('Список групп')


def group_posts(request, slug):
    # Функция get_object_or_404 получает по заданным критериям объект
    # из базы данных или возвращает сообщение об ошибке, если объект не найден.
    # В нашем случае в переменную group будут переданы объекты модели Group,
    # поле slug у которых соответствует значению slug в запросе
    group = get_object_or_404(Group, slug=slug)

    # Метод .filter позволяет ограничить поиск по критериям.
    # Это аналог добавления
    # условия WHERE group_id = {group_id}
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
  <title>
    {% block title %}
        СоцСеть of tommorow
    {% endblock %}
  </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
  <link rel="apple-touch-icon"
    sizes="180x180"
    href="{% static 'img/fav/apple-touch-icon.png' %}">
  <link rel="icon"
    type="image/png"
    sizes="32x32"
    href="{% static 'img/fav/favicon-32x32.png' %}">
  <link rel="icon"
    type="image/png"
    sizes="16x16"
    href="{% static 'img/fav/favicon-16x16.png' %}">
  <meta name="msapplication-TileColor" content="#000">
  <meta name="theme-color" content="#ffffff">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
  <main>
    <header>
      {% include 'includes/header.html' %}
    </header>
    {% block content %}
        Контент не подвезли :(
    {% endblock %}
  </main>
  <footer>
    {% include 'includes/footer.html' %}
  </footer>
</body>
</html>

yatube/templates/includes/footer.html
<!-- templates\includes\footer.html -->
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>
    Подвал
  </title>
</head>
<body>
 <!-- Использованы классы бустрапа: -->
 <!-- border-top: создаёт тонкую линию сверху блока -->
 <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
 <!-- py-3: контент внутри размещается с отступом сверху и снизу -->
 <footer class="border-top text-center py-3">
   <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
   <p>© 2022 Copyright <span style="color:red">Ya</span>tube</p>
 </footer>
</body>
</html>

yatube/templates/includes/header.html
<!-- templates\includes\header.html -->
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>
    Шапка Сайта
  </title>
  <link rel="apple-touch-icon" sizes="180x180" href={% static 'img/fav/apple-touch-icon.png' %}">
  <link rel="icon" type="image" href={% static 'img/fav/fav.ico' %}" >
  <link rel="icon" type="image/png" sizes="16x16" href={% static 'img/fav/favicon-16x16.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href={% static 'img/fav/favicon-32x32.png' %}">
  <meta name="msapplication-TileColor" content="#000">
  <meta name="theme-color" content="#ffffff">
  <!-- Подключен файл со стандартными стилями бустрап -->
  <link rel="stylesheet" href={% static 'css/bootstrap.min.css'%}>
</head>
<body>
  <header>
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="index.html">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
      <span style="color:red">Ya</span>tube
      </a>
    </div>
    </nav>
  </header>
</body>
</html>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title%}
  Записи группы {{ group.title }}
{% endblock %}
{% block content %}
<body>
  <main>
    <div class="container">
      <h1> Записи группы {{ group.title }} </h1>
        <p>
          {{ group.description }}
        </p>
      {% for post in posts %}
         <ul>
           <li>Автор: {{ post.author.get_full_name }}</li>
           <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
         </ul>
         <p>{{ post.text }}</p>
         {% if not forloop.last %}
           <hr>
         {% endif %}
      {% endfor %}
    </div>
  </main>
</body>
{% endblock %}

yatube/templates/posts/index.html
<!-- templates/posts/index.html -->
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <main>
    <div class="container">
      <h1> Последние обновления на сайте </h1>
      {% for post in posts %}
        <ul>
          <li> Автор: {{ post.author.get_full_name }}</li>
          <li> Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
        </ul>
        <p>{{ post.text }}</p>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи этой группы</a>
        {% endif %}
        {% if not forloop.last %}
          <hr>
        {% endif %}
      {% endfor %}
    </div>
  </main>
</body>
</html>
{% endblock %}